python: &python
  docker:
    - image: python:3.6.6
  working_directory: ~/circleci
  docker_layer_caching: true

jobs:
  stylecheck_and_test:
    <<: *python
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      # run test
      - run:
          name: lint
          command: |
            . venv/bin/activate
            flake8 --exclude=venv .

workflows:
  version: 2
  build-workflow:
    jobs:
      - stylecheck_and_test:
          context: org-global
          filters:
            branches:
              only:
                  - /.*/
            tags:
              only: /.*/
